/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package functional_ramming;

import java.util.concurrent.TimeUnit;

public class App {

    public static void main(String[] args) throws Exception {
        GameFrame g = new GameFrame();

        while (g != null) {
            g.writeSize();
            TimeUnit.MILLISECONDS.sleep(100);
        }

    }
}
