/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package functional_ramming;

import java.awt.BorderLayout;

public class App {

    public static void main(String[] args) throws Exception {
        GameFrame f = new GameFrame();

        Arena a = new Arena();
        
        Vector pos = new Vector(50, 250);
        Vector dir = new Vector(4.0 / 5.0, 3.0 / 5.0);
        double speed = 5;
        double size = 20;
        //Creature c = new Creature(pos, dir, speed, size);
        //a.addCreature(c);

        Rambda r = new Rambda(pos, dir, size, 6);
        RambdaController rc = new RambdaController(r);

        a.addCreature(r);

        ArenaPanel ap = new ArenaPanel(a);
        f.addKeyListener(rc);

        f.add(ap, BorderLayout.CENTER); 

        f.pack();
        f.setVisible(true);

        GameLoop gl = new GameLoop(a, ap);

        gl.run();
        
    }
}
